### ISSUE TITLE
Calcul de conservation à partir d'un profil

### ISSUE THREAD

**Issue by elolaine** [meetU-MasterStudents/2018---2019-Equipe-8#56]
La mesure la plus basique de conservation à partir d'un profil est le contenu d'information calculé avec l'entropie de Shannon. Vous pouvez trouver une explication de cette mesure ici : 
https://www.ncbi.nlm.nih.gov/Class/Structure/pssm/pssm_viewer.cgi?mode=help&q=6
En gros, pour chaque position, vous calculez la somme des fréquences pondérées par un facteur qui prends en compte une fréquence "background". Ce background peut être tiré des données que vous regardez ou de la matrice BLOSUM.

**Comment by fspecque** [comment]
Si vous aviez répondu par mail, je n'ai effectivement pas reçu la réponse...
En tous cas merci beaucoup pour votre aide, je vous recontacterai si nous décidons d'utiliser MUSCLE.
Cordialement.

**Comment by elolaine** [comment]
vous voulez dire JET2?

**Comment by elolaine** [comment]
(Et vous ne voulez pas utiliser un autre potentiel que DOPE ?
S. Grudinin était venu présenter SBROD (https://gitlab.inria.fr/grudinin/sbrod )… la conférence CASP a lieu en ce moment, et ce potentiel est classé comme le meilleur en single-model (et 9ème toutes méthodes confondues : http://predictioncenter.org/casp13/zscores_final.cgi). Et en plus il prend uniquement les atomes du squelette en entrée, donc c’est parfait pour vous !)

**Comment by elolaine** [comment]
Une autre possibilité : le package MIToS
 https://mybinder.org/v2/gh/diegozea/lcqb-internal-seminar-mitos/master?filepath=GaussDCA%20contact%20prediction%20AUC%20using%20MIToS.ipynb
Il permet de calculer la conservation et aussi des métriques de coévolution à partir d'un alignement multiple (à ce moment là, il faut que l'équipe amont vous fournisse les alignements multiples). Et il utilise les background frequencies de BLOSUM62! (mais je ne sais pas où il les a trouvées...)
