### ISSUE TITLE
Using Path from pathlib

### ISSUE THREAD

**Issue by agagelin** [meetU-MasterStudents/2018---2019-Equipe-8#58]
https://github.com/meetU-MasterStudents/2018---2019-Equipe-8/blob/5138b0a2b11c34279386520b3c6beb892972affc/TEST_best_score2.py#L38

Il vaut mieux utiliser la classe `Path` de `pathlib` quand tu utilises des chemins, ça les rend compatibles avec windows.

Utilisation:
```python
from pathlib import Path
path = Path('/ton/chemin') # Vaut "/ton/chemin" pour Unix et "\ton\chemin" pour Windows
new_path = path / "dir" # Vaut "/ton/chemin/dir" pour Unix et "\ton\chemin\dir" pour Windows
```

**Comment by Joffrin** [comment]
modifé dans `parsers.compute_structure`
