### ISSUE TITLE
Benchmark process

### ISSUE THREAD

**Issue by agagelin** [meetU-MasterStudents/2018---2019-Equipe-8#60]
Voici le cahier des charges provisoire du benchmark. Il faudrat surement modifier la fonction predict en conséquences.
Voici les étapes principales :
 

1. Parser le fichier becnmark.list. Dans ce fichier, chaque cible est associée à une famille et le degré de similarité de la cible et de la famille est indiqué (par ordre décroissant de similarité: famille, superfamille et fold).
2. Une prédiction doit être faite à partir du fichier foldrec de la cible. Le fichier predict doit renvoyer les 10 familles qu'il a trouvé le plus similaire à la cible.
3. Comparer la famille de la cible dans le benchmark avec les prédictions. La famille de la cible est-elle dans les 10 premiers ? Si oui, à quelle position ?

Des analyses avec de beaux graphs peuvent être fait ensuite.

**Comment by yvan-sraka** [comment]
@agagelin quel genre de graphiques produire pour représenter les données d'un façon plus clair que ?

![47206186_294060104567859_8263843881565552640_n](https://user-images.githubusercontent.com/705213/49437250-f61af000-f7b2-11e8-8c19-4a73afa7d7e7.jpg)

Peut-être que cela peut faire l'objet d'une autre issue ?
